name: llm-sim-single-chip-gpu
channels:
  - conda-forge
  - pytorch
  - huggingface
  - nvidia
  - defaults

dependencies:
  # Python
  - python=3.10

  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0

  # Deep learning frameworks (GPU support)
  - pytorch>=2.0.0
  - pytorch-cuda=11.8  # CUDA 11.8 support
  - transformers>=4.30.0
  - huggingface_hub>=0.16.0

  # Data manipulation and visualization
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0

  # Utilities
  - tqdm>=4.64.0
  - pyyaml>=6.0
  - requests>=2.25.0

  # Development tools
  - pytest>=7.0.0
  - black>=22.0.0
  - flake8>=5.0.0
  - mypy>=1.0.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0

  # Documentation
  - sphinx>=5.0.0
  - sphinx-rtd-theme>=1.0.0
  - sphinx-autodoc-typehints>=1.12.0

  # Package management
  - pip>=21.0.0

  # Additional packages via pip (not available in conda)
  - pip:
    - accelerate>=0.20.0
    - datasets>=2.0.0
    - tokenizers>=0.13.0
    - safetensors>=0.3.0



